### authenticate user
WEBSOCKET ws://localhost:3000/chat
Content-Type: application/json

{
  "type": "user_auth", "payload": {"userName": "Sandor Clegane", "password": "Test1234"}
}


### connect user
WEBSOCKET ws://localhost:3000/chat
Content-Type: application-json // Used for content highlighting only

{
 "type": "user_connect", "payload": {"userID": 1, "accessToken": "Test1234"}
}
=== wait-for-server
{
 "type": "user_connect", "payload": {"userID": 2, "accessToken": "Test1234"}
}

### join to room and send message
WEBSOCKET ws://localhost:3000/chat
Content-Type: application-json // Used for content highlighting only

{
 "name": "user_join_to_room", "payload": {"userID": 1, "roomID": 1, "roomName": "Room 1"}
}
=== wait-for-server
{
 "name": "user_join_to_room", "payload": {"userID": 2, "roomID": 1, "roomName": "Room 1"}
}
=== wait-for-server
{
 "name": "room_message", "payload": {"userID": 1, "roomID": 1, "message": "Yo dudes!"}
}


### create direct room
WEBSOCKET ws://localhost:3000/chat
Content-Type: application-json // Used for content highlighting only

{
 "name": "user_create_direct_room", "payload": {"creatorID": 1, "inviteeID": 2, "message": "Hello, Alex!"}
}

### send direct message
WEBSOCKET ws://localhost:3000/chat
Content-Type: application-json // Used for content highlighting only

{
 "name": "direct_message", "payload": {"userID": 1, "receiverID": 2, "roomID": 1, "message": "Arya, how are you?"}
}

### get room messages
WEBSOCKET ws://localhost:3000/chat
Content-Type: application-json // Used for content highlighting only

{
 "name": "user_connect", "payload": {"userID": 1, "accessToken": "Test1234"}
}
=== wait-for-server
{
 "name": "user_join_to_room", "payload": {"userID": 1, "roomID": 1, "roomName": "Room 1"}
}
=== wait-for-server
{
 "name": "user_get_room_messages", "payload": {"userID": 1, "roomID": 1}
}
=== wait-for-server
###
#{
# "name": "user_create_direct_room", "payload": {"creatorID": 1, "inviteeID": 2, "message": "Hello, Alex!"}
#}
#=== wait-for-server
#{
# "name": "user_join_to_room", "payload": {"userID": 1, "roomID": 1, "roomName": "Room 1"}
#}
###
#=== wait-for-server
#{
# "name": "user_join_to_room", "payload": {"userID": 2, "roomID": 1, "roomName": "Room 1"}
#}
#=== wait-for-server






### Request with client messages
#// It is possible to specify client messages in request body. Use '===' to separate messages.
#// Add '=== wait-for-server' above a message to send it after a server response is received.
#// To wait for N responses, add '=== wait-for-server' N times.
#WEBSOCKET ws://{{$exampleServer}}/ws
#Content-Type: application/json // We use it for highlighting
#
#===
#{
#  "message": "Hello, server!",
#  "repeat": 3
#}
#=== wait-for-server
#=== wait-for-server
#{
#  "message": "We send this message...",
#  "repeat": 0
#}
#===
#{
#  "message": "And this message together",
#  "repeat": 1
#}
#
#### Requests with scripts
#// Also, we can use scripts for sending messages to server and verifying messages from the server.
#WEBSOCKET ws://{{$exampleServer}}/ws
#Content-Type: application/json
#
#{
#  "message": "Beginning message"
#}
#
#> {%
#    var i = 0
#    response.body.onEachMessage((message, unsubscribe, output) => {
#        i++
#        const jsonMessage = JSON.parse(message); // We know that our sample server returns JSON
#        client.test("Server sent a JSON with 'message' property: " + i, () => {
#            client.assert(jsonMessage.message !== undefined)
#        });
#        if (jsonMessage.message.includes("finish")) {
#            unsubscribe() // remove current listener
#            return
#        }
#
#        if (i === 5) {
#            output(JSON.stringify({
#                message: "finish"
#            }));
#        } else {
#            output(JSON.stringify({
#                message: "Message from the script: " + i
#            }));
#        }
#    }, () => {
#        client.log("We stopped listening for WebSocket from the current 'onEachMessage' call!")
#    });
#%}